name: Ruby

on: push


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
   
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        with:
          source_file: 'public'
          destination_repo: 'rmagomeromdlive/mobile_dist_test'
          destination_folder: 'release'
          user_email: 'rmagomeromdlive@mdlive.com'
          user_name: 'rmagomeromdlive'
          commit_message: 'test commit'