name: Ruby

on: push

env:
  SOURCE: output/${{github.run_number}}
  OUTPUT: README.md
  TOKEN: ${{secrets.TOKEN_GITHUB}}


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          token: ${{secrets.TOKEN_GITHUB}}
      - run: |
          echo -e "starting update to gh-pages"
          mkdir -p $SOURCE
          cd $SOURCE
          git config --global user.email rmagomeromdlive@mdlive.com
          git config --global user.name rmagomeromdlive
          git clone --depth 1 --quiet --branch=main https://github.com/rmagomeromdlive/mobile_dist_test.git master
          ls
          cd master
          cat README.md
          rm -rf .git
          cd ../..

      - name: Pushes to repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        with:
          source_file: ${{env.OUTPUT}}
          destination_repo: 'rmagomeromdlive/mobile_dist_test'
          user_email: 'rmagomeromdlive@mdlive.com'
          user_name: 'rmagomeromdlive'
          commit_message: 'Hopefully this works this time'

